### ISSUE TITLE
vJunos-switch unable to connect to QEMU monitor

### ISSUE THREAD

**Issue by mpenning** [hellt/vrnetlab#197]
Under debian bookworm, I built a vJunos-switch image from `vJunos-switch-23.2R1.14.qcow2` with `hellt/vrnetlab` v0.16.0 and got the following when I tried to boot into `containerlab`...

Running `docker logs -f <containerid_hash>`...

```none
2024-06-07 11:40:49,142: vrnetlab   INFO     Unable to connect to qemu monitor (port 4000), retrying in a second (attem)
2024-06-07 11:40:50,143: vrnetlab   INFO     Unable to connect to qemu monitor (port 4000), retrying in a second (attem)
Traceback (most recent call last):
  File "/launch.py", line 185, in <module>
    vr.start()
  File "/vrnetlab.py", line 762, in start
    vm.work()
  File "/vrnetlab.py", line 680, in work
    self.check_qemu()
  File "/vrnetlab.py", line 694, in check_qemu
    self.start()
  File "/vrnetlab.py", line 216, in start
    raise QemuBroken(
vrnetlab.QemuBroken: Unable to connect to qemu monitor on port 4000
```

My containerlab is:

```none
$ sudo containerlab version
  ____ ___  _   _ _____  _    ___ _   _ _____ ____  _       _
 / ___/ _ \| \ | |_   _|/ \  |_ _| \ | | ____|  _ \| | __ _| |__
| |  | | | |  \| | | | / _ \  | ||  \| |  _| | |_) | |/ _` | '_ \
| |__| |_| | |\  | | |/ ___ \ | || |\  | |___|  _ <| | (_| | |_) |
 \____\___/|_| \_| |_/_/   \_\___|_| \_|_____|_| \_\_|\__,_|_.__/

    version: 0.54.2
     commit: 9ecdf0e2
       date: 2024-04-11T12:01:05Z
     source: https://github.com/srl-labs/containerlab
 rel. notes: https://containerlab.dev/rn/0.54/#0542
```

How do I fix this?

**Comment by mpenning** [comment]
> How do I fix this?

@hellt I managed to boot a couple of vJunos-switch images on a Digital Ocean droplet with 16GB of RAM... I will close this out since I think my original problem was due to insufficient RAM to boot the Junos docker image.

**Comment by hellt** [comment]
Great @mpenning ! Thanks for circling back on this
