### ISSUE TITLE
vMX Failed to Boot - Could not set up host forwarding rule tcp 57400

### ISSUE THREAD

**Issue by michkime** [hellt/vrnetlab#246]
Always having below error for any version 20/21/22 (didn't try any older version)

Error: vrnetlab   INFO     STDERR: qemu-system-x86_64: Could not set up host forwarding rule 'tcp:0.0.0.0:57400-10.0.0.15:57400'

```
2024-08-24 12:06:00,198: launch     DEBUG    Environment variables: environ({'PATH': '/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin', 'HOSTNAME': 'vmx', 'TERM': 'xterm', 'DOCKER_NET_V4_ADDR': '172.20.20.0/24', 'CLAB_LABEL_CLAB_NODE_TYPE': '', 'CLAB_LABEL_CLAB_NODE_GROUP': '', 'CLAB_LABEL_CLAB_NODE_LAB_DIR': '/root/zclab-vmx/clab-sros-vmx/vmx', 'CLAB_LABEL_CLAB_TOPO_FILE': '/root/zclab-vmx/srosvmx.yml', 'DOCKER_NET_V6_ADDR': '2001:172:20:20::/64', 'PASSWORD': 'admin@123', 'CONNECTION_MODE': 'tc', 'USERNAME': 'admin', 'CLAB_LABEL_CLAB_NODE_NAME': 'vmx', 'CLAB_INTFS': '1', 'CLAB_LABEL_CLAB_NODE_KIND': 'juniper_vmx', 'CLAB_LABEL_CONTAINERLAB': 'sros-vmx', 'DEBIAN_FRONTEND': 'noninteractive', 'HOME': '/root', 'LC_CTYPE': 'C.UTF-8'})
2024-08-24 12:06:00,198: vrnetlab   DEBUG    Creating overlay disk image
2024-08-24 12:06:00,232: vrnetlab   DEBUG    Creating overlay disk image
2024-08-24 12:06:00,269: vrnetlab   DEBUG    Starting vrnetlab VMX
2024-08-24 12:06:00,270: vrnetlab   DEBUG    VMs: [<__main__.VMX_vcp object at 0x7fa8296b1df0>, <__main__.VMX_vfpc object at 0x7fa8296b1e80>]
2024-08-24 12:06:00,270: vrnetlab   DEBUG    VM not started; starting!
2024-08-24 12:06:00,270: vrnetlab   INFO     Starting VMX_vcp
2024-08-24 12:06:00,272: vrnetlab   DEBUG    qemu cmd: qemu-system-x86_64 -enable-kvm -display none -machine pc -monitor tcp:0.0.0.0:4000,server,nowait -serial telnet:0.0.0.0:5000,server,nowait -m 2048 -cpu host -smp 1 -drive if=ide,file=/vmx/re/junos-vmx-x86-64-21.2R1.10-overlay-overlay.qcow2 -drive if=ide,file=/vmx/re/vmxhdd.img -usb -drive id=my_usb_disk,media=disk,format=raw,file=/vmx/re/metadata-usb-re.img,if=none -device usb-storage,drive=my_usb_disk -smbios "type=0,vendor=Juniper" -smbios "type=1,manufacturer=VMX,product=VM-vcp_vmx2-161-re-0,version=0.1.0" -device e1000,netdev=p00,mac=0C:00:1f:dc:e4:00 -netdev user,id=p00,net=10.0.0.0/24,tftp=/tftpboot,hostfwd=tcp:0.0.0.0:22-10.0.0.15:22,hostfwd=udp:0.0.0.0:161-10.0.0.15:161,hostfwd=tcp:0.0.0.0:830-10.0.0.15:830,hostfwd=tcp:0.0.0.0:80-10.0.0.15:80,hostfwd=tcp:0.0.0.0:443-10.0.0.15:443,hostfwd=tcp:0.0.0.0:9339-10.0.0.15:9339,hostfwd=tcp:0.0.0.0:57400-10.0.0.15:57400,hostfwd=tcp:0.0.0.0:6030-10.0.0.15:6030,hostfwd=tcp:0.0.0.0:32767-10.0.0.15:32767,hostfwd=tcp:0.0.0.0:8080-10.0.0.15:8080,hostfwd=tcp::17400-10.0.0.15:57400 -device virtio-net-pci,netdev=vcp-int,mac=0C:00:6f:5e:d9:01 -netdev tap,ifname=vcp-int,id=vcp-int,script=no,downscript=no
2024-08-24 12:06:00,328: vrnetlab   INFO     STDOUT: 
2024-08-24 12:06:00,329: vrnetlab   INFO     STDERR: qemu-system-x86_64: Could not set up host forwarding rule 'tcp:0.0.0.0:57400-10.0.0.15:57400'

2024-08-24 12:06:00,333: vrnetlab   INFO     Unable to connect to qemu monitor (port 4000), retrying in a second (attempt 1)
2024-08-24 12:06:01,334: vrnetlab   INFO     Unable to connect to qemu monitor (port 4000), retrying in a second (attempt 2)
2024-08-24 12:06:02,335: vrnetlab   INFO     Unable to connect to qemu monitor (port 4000), retrying in a second (attempt 3)

...

2024-08-24 12:06:59,415: vrnetlab   INFO     Unable to connect to qemu monitor (port 4000), retrying in a second (attempt 60)
Traceback (most recent call last):
  File "/launch.py", line 484, in <module>
    vr.start()
  File "/vrnetlab.py", line 650, in start
    vm.work()
  File "/vrnetlab.py", line 534, in work
    self.check_qemu()
  File "/vrnetlab.py", line 548, in check_qemu
    self.start()
  File "/launch.py", line 76, in start
    super(VMX_vcp, self).start()
  File "/vrnetlab.py", line 241, in start
    raise QemuBroken(
vrnetlab.QemuBroken: Unable to connect to qemu monitor on port 4000

```

Details of running error:
[vmx_error_57400.txt](https://github.com/user-attachments/files/16739309/vmx_error_57400.txt)

Details of image creation: 
(57400 was fine during image creation process)
[vrnetlab_make_vmx-bundle-20.2R3-S2.5.tgz.txt](https://github.com/user-attachments/files/16739306/vrnetlab_make_vmx-bundle-20.2R3-S2.5.tgz.txt)

Workaround to make it running fine: Remove gnmi forwarding tcp 57400 before make new vMX image
[vrnetlab_vmx_wa_remove-57400.txt](https://github.com/user-attachments/files/16739312/vrnetlab_vmx_wa_remove-57400.txt)

No issue with SROS/SRL.

**Comment by hellt** [comment]
ah, good call @michkime !

There was a leftover, fixed it in https://github.com/hellt/vrnetlab/pull/247
you can do a repull of the master branch and rebuild the image
